name: Action Workflow

on:
    push:
        branches:
            - main

jobs:
  run-github-actions:
    name: "Simple Action Workflow"
    runs-on: ubuntu-latest
    steps:
      - name: View all the files
        run: |
          pwd
          ls -a

    
      - name: Checkout
        uses: actions/checkout@v1

      - name: View all the files after checkout
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
                
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with: 
            who-to-greet: John

      - name: "Log Gretting Time"
        run: echo "${{ steps.greet.outputs.time }}"