name: Context FLOW
on:
    push:
        branches:
            - context

jobs:
    setup-basic-context:
        name: Setup Basic Github Context
        runs-on: ubuntu-latest
        env:
            GITHUB_CONTEXT: ${{ toJSON(github) }}
        steps:
            - run: |
                  echo "${{github.repository}}"
                  echo ${github.repository_owner}
                  echo ${github.actor}
                  echo ${github.workflow}
