name: Context FLOW
on:
    push:
        branches:
            - context

jobs:
    functions:
        runs-on: ubuntu-latest
        steps:
            - run: |
                  echo $${{contains('hello','hey')}}
                  echo $${{startsWith('Flutter Nepal','Flutter')}}
                  echo $${{endsWith('Blockchain Nepal','Nepal')}}

    setup-basic-context:
        name: Setup Basic Github Context
        runs-on: ubuntu-latest
        env:
            GITHUB_CONTEXT: ${{ toJSON(github) }}
        steps:
            - run: |
                  echo $GITHUB_CONTEXT
