name: ENV FLOW
on:
  push:
    branches:
      - "main"

env:
  WF_ENV: A simple ENV variable

jobs:
  Log_ENV_variables:
    name: Log ENV variables
    runs-on: ubuntu-latest
    steps:
      - name: "Log WF ENV"
        run:  echo "${WF_ENV}"