name: ENV FLOW
on:
  push:
    branches:
      - "main"

env:
  WF_ENV: This is basic environment variable

jobs:
  Log_ENV_variables:
    name: Log ENV variables
    runs-on: ubuntu-latest
    env:
      WF_USER: admin
      WF_PASS: password

    steps:
      - name: "Log WF ENV"
        env:
          WF_STEP_KEY: LOGIN_STEP
        run: |
          echo $WF_BASE_URL
          echo "${WF_ENV}"
          echo "Login with ${WF_USER} and ${WF_PASS}"
          echo "Login step ${WF_STEP_KEY}"
