name: ENV FLOW
on:
  push:
    branches:
      - "main"

env:
  WF_ENV: A simple ENV variable

jobs:
  Log_ENV_variables:
    name: Log ENV variables
    runs-on: ubuntu-latest
    env:
      WF_USER: admin
      WF_PASS: password

    steps:
      - name: "Log WF ENV"
        run:  |
          echo "${WF_ENV}"
          echo "Login with ${WF_USER} and ${WF_PASS}"