name: Matrix flow

on:
    push:
        branches:
            - matrix

jobs:
    node-version:
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]
                node_version: [8, 8, 10]

        name: Node Version Installer
        runs-on: ${{matrix.os}}
        steps:
            - name: Log Node Version
              run: node -v
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{matrix.node_version}}
            - run: node -v
