name: Shedule Action
on:
  pull_request:
    types:
      - opened
  # schedule:
  #   - cron: "*/1 * * * *"
jobs:
    simple-schedule:
     name: Simple Schesule
     runs-on: ubuntu-latest
     steps:
       - name: Log String
         run: echo "Hello World"